# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TplOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # AFNetworking 网络请求
  pod 'AFNetworking', '~> 3.2.1'
  #pod 'SDWebImage', '~> 5.0.0-beta3'
  pod 'Masonry', '~> 1.1.0'
  #pod 'YYKit', '~> 1.0.9'
  #pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
  #pod 'MJExtension', '~> 3.0.15.1'
  #pod 'MJRefresh', '~> 3.1.15.7'
  #pod 'MGSwipeTableCell', '~> 1.6.7'
  #pod 'WebViewJavascriptBridge', '~> 6.0.3'
  #pod 'FMDB', '~> 2.7.5'
  #pod 'CocoaAsyncSocket', '~> 7.6.3'
  #pod 'GPUImage', '~> 0.1.7'
  #pod 'AsyncDisplayKit', '~> 2.2.1'
  #pod 'SAMKeychain', '~> 1.5.3'
  #pod 'pop', '~> 1.0.12'
  #pod 'AwesomeMenu', '~> 1.0.0'
  #pod 'MMDrawerController', '~> 0.6.0'
  #pod 'CocoaLumberjack', '~> 3.4.2'
  #pod 'SocketRocket', '~> 0.5.1'
  #pod 'JazzHands', '~> 2.0.8'

  target 'TplOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TplOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
